import deadpool from "../imgs/deadpool.jpg";
import mcu from "../imgs/mcu.jpg";
import rdj from "../imgs/rdj.jpg";
import batman from "../imgs/batman.jpg";
import giancarlo from "../imgs/giancarlo.jpg";
import dexter from "../imgs/dexter.jpg";
import reaper from "../imgs/reaper.jpg";

export const dummyDataMovies = [
	{
		author: { personal_info: { fullname: "Marcin Prokop", profile_img: rdj } },
		category: "movie",
		comments: 15,
		description:
			"A movie about two guys struggling for life. Obcy: Romulus rozgrywa się na odległej kolonii górniczej, skąd Rain (Cailee Spaeny) pragnie uciec wraz ze swoim ",
		img: deadpool,
		genre: "action",
		likes: 8,
		pegi: 12,
		peopleAwaiting: 562,
		ratedByCount: 18242,
		rating: 7.8,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone.",
		title: "I am legend 2",
		length: 128,
		year: 2022,
	},
	{
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: dexter },
		},
		category: "movie",
		comments: 15,
		description: "A movie about two guys struggling for life",
		img: rdj,
		genre: "Thriller",
		likes: 15,
		pegi: 12,
		peopleAwaiting: 562,
		ratedByCount: 2422,
		rating: 6.2,
		review:
			"Lovely movie with a few problems. The director did a really good job when it comes to capturing the emotions. On top of that it was really impressive work from all the actors and actresses.",
		title: "Armand",
		length: 128,
		year: 2022,
	},
	{
		title: "Civil War",
		category: "series",
		img: batman,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: giancarlo },
		},
		rating: 6.9,
		genre: "Romance",
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		pegi: 12,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "I am legend 2",
		category: "movie",
		img: giancarlo,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: mcu },
		},
		rating: 5.4,
		genre: "Mafia",
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone.",
		likes: 8,
		pegi: 12,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Armand",
		category: "movie",
		img: mcu,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: batman },
		},
		rating: 7.1,
		genre: "Psychological",
		review:
			"Lovely movie with a few problems. The director did a really good job when it comes to capturing the emotions.",
		pegi: 12,
		likes: 15,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		pegi: 12,
		genre: "Fantasy",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		pegi: 12,
		genre: "War",
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		pegi: 12,
		rating: 4.4,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		genre: "Criminal",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
			pegi: 12,
		},
		rating: 4.4,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		genre: "Biography",
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			pegi: 12,
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		genre: "Biography",
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		pegi: 12,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		genre: "Biography",
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		genre: "Biography",
		pegi: 12,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		genre: "Biography",
		pegi: 12,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		genre: "Biography",
		pegi: 12,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		genre: "Biography",
		pegi: 12,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
	{
		title: "Civil War",
		category: "series",
		img: dexter,
		author: {
			personal_info: { fullname: "Marcin Prokop", profile_img: rdj },
		},
		rating: 4.4,
		genre: "Biography",
		pegi: 12,
		review:
			"Absolutely abysmal movie. I do not recommend watching it to anyone",
		likes: 8,
		ratedByCount: 18242,
		peopleAwaiting: 562,
		comments: 15,
		description: "A movie about two guys struggling for life",
		year: 2022,
		length: 128,
	},
];
